name: Rust

on:
  push:
    branches: [ master, v*.* ]
  pull_request:
    branches: [ master, v*.* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
       profile: minimal
       components: rust-fmt, rust-clippy
    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - uses: actions-rs/clippy-check@v1.0.7
